name: Build and Push Multi-Architecture Docker Image

on:
  push:
    branches:
      - main
      - '*'
    tags:
      - '*'

  pull_request:
    branches:
      - dev

  workflow_dispatch:

  repository_dispatch:
    types:
      - trigger-build

jobs:
  build-and-push:
    runs-on: self-hosted

    container:
      image: ubuntu:22.04
    
    steps:

    - name: Install Git
      run: |
        apt-get update
        apt-get install -y git

    - name: Install vcs
      run: |
        apt-get update
        apt-get install -y python3-pip
        pip3 install vcstool

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}
      
    - name: Configure Git for https access
      run: |
        git config --global url."https://${{ secrets.PAT_TOKEN }}@github.com/".insteadOf "https://github.com/"

    - name: Import repositories using vcs
      run: |
        vcs import --recursive < wisevision_core.repos

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image for multiple architectures
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 \
          --tag ${{ secrets.DOCKER_HUB_USERNAME }}/ros_with_wisevision_msgs_and_wisevision_core:humble --push .
