name: Build and run ROS2 tests

on:
  pull_request:
    branches: [ dev , main, 'stabilization/**' ]
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:

    runs-on: wisevision-runner

    continue-on-error: true

    container:
      image: ros:humble-ros-base

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: wisevision_core_ws/src/wisevision_core

    - name: Install dependencies
      run: |
        apt-get update
        rosdep update --include-eol-distros
        cd wisevision_core_ws
        rosdep install --from-paths src --ignore-src -r -y --rosdistro humble


    - name: Build and run 
      run: |
        . /opt/ros/humble/setup.sh
        cd wisevision_core_ws
        colcon build

    - name: Clean up workspace
      if: always()
      run: |
        sudo rm -rf wisevision_core_ws

